- name: Ensure persistent storage folders exist
  hosts: storage_nodes
  tasks:
    - name: Ensure /opt/pvc dir is present
      file:
        path: /opt/pvc
        state: directory

- name: Ensure persistent volumes are available for redis
  hosts: redis_nodes
  tasks:
    - name: Check if /opt/pvc/vd0 file exists
      stat:
        path: /opt/pvc/vd0
      register: vd0
    - name: Create /opt/pvc/vd0 file
      shell:
        cmd: dd if=/dev/zero of=/opt/pvc/vd0 bs=1M count=2300
      when: not vd0.stat.exists
    - name: Create ext4 fs on /opt/pvc/vd0
      filesystem:
        fstype: ext4
        dev: /opt/pvc/vd0
    - name: Make mount point for /mnt/file/vd0
      file:
        path: /mnt/file/vd0
        state: directory
    - name: Mount /opt/pvc/vd0 to /mnt/file
      mount:
        path: /mnt/file/vd0
        src: /opt/pvc/vd0
        state: mounted
        fstype: ext4

- name: Ensure persistent volumes are available for prometheus
  hosts: prometheus_nodes
  tasks:
    - name: Check if /opt/pvc/vd1 file exists
      stat:
        path: /opt/pvc/vd1
      register: vd1
    - name: Create /opt/pvc/vd1 file
      shell:
        cmd: dd if=/dev/zero of=/opt/pvc/vd1 bs=1M count=4096
      when: not vd1.stat.exists
    - name: Create ext4 fs on /opt/pvc/vd1
      filesystem:
        fstype: ext4
        dev: /opt/pvc/vd1
    - name: Make mount point for /mnt/file/vd1
      file:
        path: /mnt/redis/vd1
        state: directory
    - name: Mount /opt/pvc/vd1 to /mnt/file
      mount:
        path: /mnt/file/vd1
        src: /opt/pvc/vd1
        state: mounted
        fstype: ext4

