---
- name: Provision VMs using Terraform
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Run terraform
      terraform:
          project_path: "{{playbook_dir}}/terraform"
          state: present
    - name: Refresh ansible inventory
      meta: refresh_inventory

- name: Wait until all nodes are up
  hosts: k8s-cluster
  gather_facts: no
  tasks:
      - name: Waiting until host is up
        wait_for_connection:

- name: Add floating IP configs to ingress nodes
  hosts: ingress
  gather_facts: no
  tasks:
    - name: Create configuration
      template:
        src: floating_ip.tmpl
        dest: /etc/sysconfig/network-scripts/ifcfg-eth0:1
    - name: Restart network
      service:
        name: network
        state: restarted

- name: Ensure kubernetes is deployed
  import_playbook: kubespray/cluster.yml

- name: Ensure kubeconfig is present on local machine
  import_playbook: download_kubeconfig.yaml

- name: Ensure needed software is installed
  import_playbook: install_software_images.yaml
