---
- name: Ensure kubeconfig is present on local machine
  import_playbook: download_kubeconfig.yaml

- name: Ensure namespaces are present
  gather_facts: no
  hosts: localhost
  connection: local
  collections:
    - community.kubernetes
  tasks:
    - name: Create assfire namespace
      community.kubernetes.k8s:
        name: assfire
        api_version: v1
        kind: Namespace
        state: present

- name: Ensure redis is deployed
  gather_facts: no
  hosts: localhost
  connection: local
  collections:
    - community.kubernetes
  tasks:
    - name: Ensure redis installation exists
      community.kubernetes.helm:
        chart_ref: redis-cluster
        chart_version: 3.1.3
        chart_repo_url: "https://charts.bitnami.com/bitnami"
        release_name: assfire-geocache
        release_state: present
        release_namespace: assfire
        release_values:
          timeout: 600
          cluster.nodes: 1
          cluster.replicas: 0
          redis.nodeSelector:
            redis_role: master
