server:
  enabled: true
  replicas: 2
  nodeSelector:
    assfire_scheduler: enabled
  labels:
    app: assfire-scheduler-server
  imagePullSecrets: []
  router:
    host: assfire-router-service.default.svc.cluster.local
    port: 50051
    ssl: false
  metrics:
    enabled: true
  log:
    level: info
  ingress:
    enabled: true
    host: assfire.org
  grpc_gateway:
    enabled: true
  service:
    labels:
      metrics: prometheus
