---
- name: Ensure cluster config is present on local machine
  hosts: kubeconfig-fetch-node
  tasks:
    - name: Fetch admin.conf to ~/.kube/config
      fetch:
        src: /etc/kubernetes/admin.conf
        dest: ~/.kube/config
        flat: yes
