stages:
  - build ci image
  - publish master ci image
  - build applications

variables:
  MASTER_BUILD_IMAGE_NAME: $CI_REGISTRY/assfire/assfire-suite/buildimage:latest
  TEMP_IMAGE_TAG_NAME: ci-$CI_COMMIT_SHORT_SHA
  BUILD_IMAGE_NAME: $CI_REGISTRY/assfire/assfire-suite/buildimage:ci-$CI_COMMIT_SHORT_SHA
  DOCKER_BUILDKIT: 1
  APPLICATION_VERSION: $CI_COMMIT_REF_NAME

build-ci-image:
  image: docker:19.03.0
  services:
    - docker:dind
  stage: build ci image
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - cd ci
    - docker build . -t $BUILD_IMAGE_NAME --cache-from $MASTER_BUILD_IMAGE_NAME --build-arg BUILDKIT_INLINE_CACHE=1
    - docker push $BUILD_IMAGE_NAME
  needs: []

publish-master-ci-image:
  image: docker:stable
  services:
    - docker:dind
  stage: publish master ci image
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $BUILD_IMAGE_NAME
    - docker tag $BUILD_IMAGE_NAME $MASTER_BUILD_IMAGE_NAME
    - docker push $MASTER_BUILD_IMAGE_NAME
  only:
    refs:
      - master
  needs:
    - build-ci-image

include:
  - apps.yml