apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-server
  labels:
    app: assfire-router-server
spec:
  replicas: {{.Values.replicas.server}}
  selector:
    matchLabels:
      app: assfire-router-server
  template:
    metadata:
      labels:
        app: assfire-router-server
    spec:
      nodeSelector:
        {{ toYaml .Values.nodeSelector.server}}
      containers:
        - name: router-server
          image: registry.gitlab.com/assfire/assfire-suite/assfire-router-server:v0.0.9
          ports:
            - containerPort: 50051
            - containerPort: 8081
          command: [ "assfire-router-server" ]
          args:
            - "--redis-cache-enabled={{.Values.cache.enabled}}"
            - "--redis-host={{.Release.Name}}-redis-master.{{.Release.Namespace}}.svc.cluster.local"
            - "--redis-port=6379"
            - "--metrics-enabled={{.Values.metrics.enabled}}"
            - "--log-level={{.Values.log.level}}"
        - name: router-grpc-gateway
          image: registry.gitlab.com/assfire/assfire-suite/assfire-router-server:v0.0.9
          ports:
            - containerPort: 8082
          command: [ "assfire-router-grpc-gateway" ]
      imagePullSecrets:
        - name: assfire-registry-key
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-maptest
  labels:
    app: assfire-router-maptest
spec:
  replicas: {{.Values.replicas.maptest}}
  selector:
    matchLabels:
      app: assfire-router-maptest
  template:
    metadata:
      labels:
        app: assfire-router-maptest
    spec:
      nodeSelector:
        {{ toYaml .Values.nodeSelector.maptest}}
      containers:
        - name: router-maptest
          image: registry.gitlab.com/assfire/assfire-suite/assfire-router-maptest:v0.0.9
          ports:
            - containerPort: 8083
      imagePullSecrets:
        - name: assfire-registry-key
