apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-server
  labels:
    metrics: prometheus
spec:
  selector:
    app: {{ .Release.Name }}-server
  ports:
    - name: grpc
      protocol: TCP
      port: 50051
      targetPort: 50051
    - name: http-metrics
      port: 8081
      targetPort: 8081
    - name: http-proxy
      port: 8082
      targetPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-maptest
  labels:
    metrics: prometheus
spec:
  selector:
    app: {{ .Release.Name }}-maptest
  ports:
    - name: maptest
      port: 8083
      targetPort: 8083