- name: Ensure osrm namespaces are present
  hosts: localhost
  connection: local
  collections:
    - community.kubernetes
  tasks:
    - name: Create osrm namespace
      community.kubernetes.k8s:
        name: osrm
        api_version: v1
        kind: Namespace
        state: present

- name: Ensure OSRM nodes are labeled properly
  hosts: localhost
  connection: local
  tasks:
    - name: Add osrm_region label to osrm worker nodes
      shell: kubectl label nodes {{item}} osrm_region={{hostvars[item].osrm_region}} --overwrite
      with_items: "{{ groups['osrm_nodes'] }}"
    - name: Add osrm_role=worker label to osrm worker nodes
      shell: kubectl label nodes {{item}} osrm_role=worker --overwrite
      with_items: "{{ groups['osrm_nodes'] }}"

- name: Ensure OSRM is deployed
  hosts: localhost
  connection: local
  collections:
    - community.kubernetes
  tasks:
    - name: Deploy Crimean region
      community.kubernetes.helm:
        chart_ref: "{{playbook_dir}}/osrm/chart"
        release_name: osrm-crimean-fd-car
        release_state: present
        release_namespace: osrm
        release_values:
          map_url: https://download.geofabrik.de/russia/crimean-fed-district-latest.osm.pbf
          osrm_region: crimean
          profile: /opt/car.lua
          storage_claim: 10Gi
          service_port: 5000
          storage_class_name: hcloud-volumes