- name: Ensure prometheus namespaces are present
  hosts: localhost
  connection: local
  collections:
    - community.kubernetes
  tasks:
    - name: Create prometheus namespace
      community.kubernetes.k8s:
        name: prometheus
        api_version: v1
        kind: Namespace
        state: present

- name: Ensure Prometheus nodes are labeled properly
  hosts: localhost
  connection: local
  tasks:
    - name: Add prometheus_role=worker label to prometheus worker nodes
      shell: kubectl label nodes {{item}} prometheus_role=worker --overwrite
      with_items: "{{ groups['prometheus_nodes'] }}"

- name: Ensure prometheus is deployed
  hosts: localhost
  connection: local
  collections:
    - community.kubernetes
  tasks:
    - name: Ensure prometheus installation exists
      community.kubernetes.helm:
        chart_ref: kube-prometheus-stack
        chart_version: 9.4.1
        chart_repo_url: "https://prometheus-community.github.io/helm-charts"
        release_name: prometheus
        release_state: present
        release_namespace: prometheus
        release_values:
          defaultRules:
            rules:
              alertmanager: false
          alertmanager:
            enabled: false
          prometheus:
            prometheusSpec:
              nodeSelector:
                prometheus_role: worker
              storageSpec:
                volumeClaimTemplate:
                  spec:
                    storageClassName: hcloud-volumes
                    resources:
                      requests:
                        storage: 10Gi
            additionalServiceMonitors:
              - name: assfire-monitoring-services
                namespaceSelector:
                  matchNames:
                    - assfire
                selector:
                  matchLabels:
                    metrics: prometheus
                endpoints:
                  - port: http-metrics
                    interval: 15s
