---
apiVersion: apps/v1
kind: Deployment
metadata:
	namespace: assfire
	name: assfire-router-deployment
	labels:
		app: assfire-router
spec:
	replicas: {{.Values.assfire_router_replicas}}
	selector:
		matchLabels:
			app: assfire-router-server
	template:
		metadata:
			labels:
				app: assfire-router-server
			spec:
				containers:
				- name: assfire-router-server
				  image: assfire-router:{{.Values.assfire_router_tag}}}
				  ports:
				    - containerPort: 50051

---
apiVersion: v1
kind: Service
metadata:
	namespace: assfire
	name: assfire-router-service
spec:
	selector:
		app: assfire-router-server
	ports:
		- protocol: TCP
		  port: 50051
		  targetPort: 50051