apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: assfire
  name: assfire-router-deployment
  labels:
    app: assfire-router
spec:
  replicas: {{.Values.assfire_router_replicas}}
  selector:
    matchLabels:
      app: assfire-router-server
  template:
    metadata:
      labels:
        app: assfire-router-server
    spec:
      containers:
        - name: assfire-router-server
          image: assfire-router:{{.Values.assfire_router_tag}}
          ports:
            - containerPort: 50051
          args:
            - "--redis-cache-enabled=true"
            - "--redis-host=assfire-geocache-redis-master"
            - "--metrics-enabled=true"
