apiVersion: v1
kind: Service
metadata:
  namespace: assfire
  name: assfire-router-service
  labels:
    metrics: prometheus
spec:
  selector:
    assfire_app: assfire-router-server
  ports:
    - name: grpc
      protocol: TCP
      port: 50051
      targetPort: 50051
    - name: http-metrics
      port: 8081
      targetPort: 8081