apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}
  labels:
    assfire_app: {{ .Release.Name }}-server
spec:
  replicas: {{.Values.replicas}}
  selector:
    matchLabels:
      assfire_app: {{ .Release.Name }}-server
  template:
    metadata:
      labels:
        assfire_app: {{ .Release.Name }}-server
    spec:
      nodeSelector:
        assfire_role: calculation-node
      containers:
        - name: assfire-sample-server
          image: registry.gitlab.com/assfire/assfire-suite/assfire-sample:@ASSFIRE_APPLICATION_RELEASE_VERSION@
          ports:
            - containerPort: 50051
            - containerPort: 8081
          command: ["assfire-sample-server"]
          args: ["--metrics-enabled=true", "--log-level=info"]
        - name: assfire-sample-grpc-gateway
          image: registry.gitlab.com/assfire/assfire-suite/assfire-sample:@ASSFIRE_APPLICATION_RELEASE_VERSION@
          ports:
            - containerPort: 8082
          command: [ "assfire-sample-grpc-gateway" ]
      imagePullSecrets:
        - name: assfire-registry-key
