replicas:
  server: 2
  maptest: 1
log:
  level: info
metrics:
  enabled: true
cache:
  enabled: true
osrm:
  local: false
nodeSelector:
  server: {"assfire_router": "enabled"}
  maptest: {"assfire_router": "enabled"}
redis:
  usePassword: false
  master:
    nodeSelector: {"assfire_router": "enabled"}
  slave:
    nodeSelector: {"assfire_router": "enabled"}
ingress:
  host: assfire.org