stages:
  - build
  - test
  - package
  - publish
  - deploy

variables:
  CMAKE_OPTIONS: |
    -DASSFIRE_APPLICATION_RELEASE_VERSION=$APPLICATION_VERSION
    -DASSFIRE_DEBUG_MODE=OFF
    -DCMAKE_BUILD_TYPE=Release
    -DASSFIRE_GENERATE_GRPC_GATEWAYS=True
    -DASSFIRE_APPS_BUILD_ALL=OFF
    -DASSFIRE_APPS_BUILD_SAMPLE=ON
    -DASSFIRE_PACKAGE_BUILD_RPM=ON

.configure:
  before_script:
    - mkdir out
    - cd out
    - cmake -DCMAKE_TOOLCHAIN_FILE="$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake" $CMAKE_OPTIONS ../
    - cd ..

build:
  extends: .configure
  stage: build
  image: $BUILD_IMAGE_NAME
  artifacts:
    paths:
      - out/*
    expire_in: 1 hour
  script:
    - cd out
    - make install package -j

test:
  image: $BUILD_IMAGE_NAME
  stage: test
  script:
    - cd out
    - make test
  dependencies:
    - build
  needs:
    - build

.install-service:
  before_script:
    - rpm -i --nodeps out/assfire-${APPLICATION_VERSION}-Linux-sample.rpm
    - rpm -i --nodeps out/assfire-${APPLICATION_VERSION}-Linux-sample-grpc-gateway.rpm

helm-lint:
  image: $BUILD_IMAGE_NAME
  stage: test
  script:
    - cd out/apps/sample/helm/assfire-sample
    - helm lint .

build-docker-server:
  image: docker:stable
  services:
    - docker:dind
  variables:
    IMAGE_TAG_NAME: latest
  stage: package
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build out --build-arg APPLICATION_NAME=sample --build-arg APPLICATION_VERSION=${APPLICATION_VERSION} -f out/apps/sample/Dockerfile -t $CI_REGISTRY/assfire/assfire-suite/assfire-sample:$TEMP_IMAGE_TAG_NAME
    - docker push $CI_REGISTRY/assfire/assfire-suite/assfire-sample:$TEMP_IMAGE_TAG_NAME
  dependencies:
    - build
  needs:
    - build
    - test

publish-docker-server:
  image: docker:stable
  services:
    - docker:dind
  stage: publish
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $CI_REGISTRY/assfire/assfire-suite/assfire-sample:$TEMP_IMAGE_TAG_NAME
    - docker tag $CI_REGISTRY/assfire/assfire-suite/assfire-sample:$TEMP_IMAGE_TAG_NAME $CI_REGISTRY/assfire/assfire-suite/assfire-sample:${APPLICATION_VERSION}
    - docker push $CI_REGISTRY/assfire/assfire-suite/assfire-sample:${APPLICATION_VERSION}
  only:
    refs:
      - tags
  needs:
    - build-docker-server

build-helm-chart:
  image: $BUILD_IMAGE_NAME
  variables:
    HELM_EXPERIMENTAL_OCI: 1
  stage: publish
  only:
    - tags
  script:
    - cd out/apps/sample/helm/assfire-sample/
    - helm registry login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - helm chart save . $CI_REGISTRY/assfire/assfire-suite/helm/assfire-sample:${APPLICATION_VERSION}
    - helm chart push $CI_REGISTRY/assfire/assfire-suite/helm/assfire-sample:${APPLICATION_VERSION}
  dependencies:
    - build
  needs:
    - build
    - build-docker-server

deploy-release:
  only:
    - tags
  when: manual
  variables:
    HELM_EXPERIMENTAL_OCI: 1
  tags:
    - assfire-deployment-node
  stage:
    deploy
  script:
    - echo "Deploying Assfire Sample"
    - helm registry login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - helm chart pull $CI_REGISTRY/assfire/assfire-suite/helm/assfire-sample:${APPLICATION_VERSION}
    - helm chart export $CI_REGISTRY/assfire/assfire-suite/helm/assfire-sample:${APPLICATION_VERSION}
    - helm upgrade -i assfire-sample -n assfire ./assfire-sample
  dependencies:
    - publish-docker-server
    - build-helm-chart
  needs:
    - publish-docker-server
    - build-helm-chart