const ROUTER_ENGINE_TYPE_CROWFLIGHT = "ROUTER_ENGINE_TYPE_CROWFLIGHT"
const ROUTER_ENGINE_TYPE_EUCLIDEAN = "ROUTER_ENGINE_TYPE_EUCLIDEAN"
const ROUTER_ENGINE_TYPE_RANDOM = "ROUTER_ENGINE_TYPE_RANDOM"
const ROUTER_ENGINE_TYPE_OSRM = "ROUTER_ENGINE_TYPE_OSRM"

const OSRM_GEOMETRY_STRAIGHT_LINE = "OSRM_GEOMETRY_STRAIGHT_LINE"
const OSRM_GEOMETRY_SIMPLIFIED = "OSRM_GEOMETRY_SIMPLIFIED"
const OSRM_GEOMETRY_FULL = "OSRM_GEOMETRY_FULL"

export default {
    ROUTER_ENGINE_TYPE_CROWFLIGHT: ROUTER_ENGINE_TYPE_CROWFLIGHT,
    ROUTER_ENGINE_TYPE_EUCLIDEAN: ROUTER_ENGINE_TYPE_EUCLIDEAN,
    ROUTER_ENGINE_TYPE_RANDOM: ROUTER_ENGINE_TYPE_RANDOM,
    ROUTER_ENGINE_TYPE_OSRM: ROUTER_ENGINE_TYPE_OSRM,

    OSRM_GEOMETRY_STRAIGHT_LINE: OSRM_GEOMETRY_STRAIGHT_LINE,
    OSRM_GEOMETRY_SIMPLIFIED: OSRM_GEOMETRY_SIMPLIFIED,
    OSRM_GEOMETRY_FULL: OSRM_GEOMETRY_FULL,
}
