apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{.Release.Namespace}}
  name: {{.Release.Name}}
  labels:
    assfire_app: {{.Release.Name}}-server
spec:
  replicas: {{.Values.server_replicas}}
  selector:
    matchLabels:
      assfire_app: {{.Release.Name}}-server
  template:
    metadata:
      labels:
        assfire_app: {{.Release.Name}}-server
    spec:
      nodeSelector:
        assfire_role: calculation-node
      containers:
        - name: assfire-tsp-server
          image: registry.gitlab.com/assfire/assfire-suite/assfire-tsp-server:@ASSFIRE_APPLICATION_RELEASE_VERSION@
          ports:
            - containerPort: 50051
            - containerPort: 8081
          command: [ "assfire-tsp-server" ]
          args:
            - "--redis-endpoint={{.Values.redis_host}}"
            - "--redis-port={{.Values.redis_port}}"
            - "--rabbit-endpoint={{.Values.rabbit_host}}"
            - "--rabbit-port={{.Values.rabbit_port}}"
        - name: assfire-tsp-grpc-gateway
          image: registry.gitlab.com/assfire/assfire-suite/assfire-tsp-server:@ASSFIRE_APPLICATION_RELEASE_VERSION@
          ports:
            - containerPort: 8082
          command: [ "assfire-tsp-grpc-gateway" ]
      imagePullSecrets:
        - name: assfire-registry-key
