macro(define_common_names component_name)
    string(TOUPPER ${PROJECT_PREFIX}_${component_name} __COMPONENT_PREFIX_${component_name})
    set(${__COMPONENT_PREFIX_${component_name}}_COMPONENT_NAME ${component_name})
    set(${__COMPONENT_PREFIX_${component_name}}_SHORT_ENGINE_NAME ${${__COMPONENT_PREFIX_${component_name}}_COMPONENT_NAME}-${${PROJECT_PREFIX}_APP_ENGINE_SUFFIX})
    set(${__COMPONENT_PREFIX_${component_name}}_SHORT_PROTO_BINDING_NAME ${${__COMPONENT_PREFIX_${component_name}}_COMPONENT_NAME}-${${PROJECT_PREFIX}_APP_PROTO_BINDING_SUFFIX})
    set(${__COMPONENT_PREFIX_${component_name}}_SHORT_CLIENT_NAME ${${__COMPONENT_PREFIX_${component_name}}_COMPONENT_NAME}-${${PROJECT_PREFIX}_APP_CLIENT_SUFFIX})
    set(${__COMPONENT_PREFIX_${component_name}}_SHORT_REVERSE_PROXY_NAME ${${__COMPONENT_PREFIX_${component_name}}_COMPONENT_NAME}-${${PROJECT_PREFIX}_APP_REVERSE_PROXY_SUFFIX})

    set(${__COMPONENT_PREFIX_${component_name}}_APP_NAME ${PROJECT_NAME}-${${__COMPONENT_PREFIX_${component_name}}_COMPONENT_NAME})
    set(${__COMPONENT_PREFIX_${component_name}}_ENGINE_NAME ${PROJECT_NAME}-${${__COMPONENT_PREFIX_${component_name}}_SHORT_ENGINE_NAME})
    set(${__COMPONENT_PREFIX_${component_name}}_PROTO_BINDING_NAME ${PROJECT_NAME}-${${__COMPONENT_PREFIX_${component_name}}_SHORT_PROTO_BINDING_NAME})
    set(${__COMPONENT_PREFIX_${component_name}}_CLIENT_NAME ${PROJECT_NAME}-${${__COMPONENT_PREFIX_${component_name}}_SHORT_CLIENT_NAME})
    set(${__COMPONENT_PREFIX_${component_name}}_REVERSE_PROXY_NAME ${PROJECT_NAME}-${${__COMPONENT_PREFIX_${component_name}}_SHORT_REVERSE_PROXY_NAME})

    message(STATUS "[name-utils] Variables defined:")
    message(STATUS "[name-utils] ${__COMPONENT_PREFIX_${component_name}}_COMPONENT_NAME = ${${__COMPONENT_PREFIX_${component_name}}_COMPONENT_NAME}")
    message(STATUS "[name-utils] ${__COMPONENT_PREFIX_${component_name}}_APP_NAME = ${${__COMPONENT_PREFIX_${component_name}}_APP_NAME}")
    message(STATUS "[name-utils] ${__COMPONENT_PREFIX_${component_name}}_SHORT_ENGINE_NAME = ${${__COMPONENT_PREFIX_${component_name}}_SHORT_ENGINE_NAME}")
    message(STATUS "[name-utils] ${__COMPONENT_PREFIX_${component_name}}_SHORT_PROTO_BINDING_NAME = ${${__COMPONENT_PREFIX_${component_name}}_SHORT_PROTO_BINDING_NAME}")
    message(STATUS "[name-utils] ${__COMPONENT_PREFIX_${component_name}}_SHORT_CLIENT_NAME = ${${__COMPONENT_PREFIX_${component_name}}_SHORT_CLIENT_NAME}")
    message(STATUS "[name-utils] ${__COMPONENT_PREFIX_${component_name}}_SHORT_REVERSE_PROXY_NAME = ${${__COMPONENT_PREFIX_${component_name}}_SHORT_REVERSE_PROXY_NAME}")
    message(STATUS "[name-utils] ${__COMPONENT_PREFIX_${component_name}}_ENGINE_NAME = ${${__COMPONENT_PREFIX_${component_name}}_ENGINE_NAME}")
    message(STATUS "[name-utils] ${__COMPONENT_PREFIX_${component_name}}_PROTO_BINDING_NAME = ${${__COMPONENT_PREFIX_${component_name}}_PROTO_BINDING_NAME}")
    message(STATUS "[name-utils] ${__COMPONENT_PREFIX_${component_name}}_CLIENT_NAME = ${${__COMPONENT_PREFIX_${component_name}}_CLIENT_NAME}")
    message(STATUS "[name-utils] ${__COMPONENT_PREFIX_${component_name}}_REVERSE_PROXY_NAME = ${${__COMPONENT_PREFIX_${component_name}}_REVERSE_PROXY_NAME}")
endmacro()