macro(define_common_vars component_name)
    message(STATUS "Defining variables for component \"${component_name}\"")
    string(TOUPPER ASSFIRE_${component_name} __COMPONENT_PREFIX_${component_name})
    set(${__COMPONENT_PREFIX_${component_name}}_COMPONENT_NAME ${component_name})
    set(${__COMPONENT_PREFIX_${component_name}}_SHORT_ENGINE_NAME ${${__COMPONENT_PREFIX_${component_name}}_COMPONENT_NAME}-${ASSFIRE_APP_ENGINE_SUFFIX})
    set(${__COMPONENT_PREFIX_${component_name}}_SHORT_API_NAME ${${__COMPONENT_PREFIX_${component_name}}_COMPONENT_NAME}-${ASSFIRE_APP_API_SUFFIX})
    set(${__COMPONENT_PREFIX_${component_name}}_SHORT_CLIENT_NAME ${${__COMPONENT_PREFIX_${component_name}}_COMPONENT_NAME}-${ASSFIRE_APP_CLIENT_SUFFIX})
    set(${__COMPONENT_PREFIX_${component_name}}_SHORT_GATEWAY_NAME ${${__COMPONENT_PREFIX_${component_name}}_COMPONENT_NAME}-${ASSFIRE_APP_GATEWAY_SUFFIX})
    set(${__COMPONENT_PREFIX_${component_name}}_SHORT_TOOL_PREFIX ${${__COMPONENT_PREFIX_${component_name}}_COMPONENT_NAME}-${ASSFIRE_APP_TOOLS_SUFFIX})

    set(${__COMPONENT_PREFIX_${component_name}}_APP_NAME ${PROJECT_NAME}-${${__COMPONENT_PREFIX_${component_name}}_COMPONENT_NAME})
    set(${__COMPONENT_PREFIX_${component_name}}_ENGINE_NAME ${PROJECT_NAME}-${${__COMPONENT_PREFIX_${component_name}}_SHORT_ENGINE_NAME})
    set(${__COMPONENT_PREFIX_${component_name}}_API_NAME ${PROJECT_NAME}-${${__COMPONENT_PREFIX_${component_name}}_SHORT_API_NAME})
    set(${__COMPONENT_PREFIX_${component_name}}_CLIENT_NAME ${PROJECT_NAME}-${${__COMPONENT_PREFIX_${component_name}}_SHORT_CLIENT_NAME})
    set(${__COMPONENT_PREFIX_${component_name}}_GATEWAY_NAME ${PROJECT_NAME}-${${__COMPONENT_PREFIX_${component_name}}_SHORT_GATEWAY_NAME})
    set(${__COMPONENT_PREFIX_${component_name}}_TOOL_PREFIX ${PROJECT_NAME}-${${__COMPONENT_PREFIX_${component_name}}_SHORT_TOOL_PREFIX})

    if (ASSFIRE_BUNDLE_INSTALL_MODE)
        set(${__COMPONENT_PREFIX_${component_name}}_INSTALL_PREFIX ${CMAKE_INSTALL_PREFIX}/apps/${${__COMPONENT_PREFIX_${component_name}}_COMPONENT_NAME})
    else()
        set(${__COMPONENT_PREFIX_${component_name}}_INSTALL_PREFIX ${CMAKE_INSTALL_PREFIX})
    endif ()

    message(STATUS "[name-utils] Variables defined:")
    message(STATUS "[name-utils] ${__COMPONENT_PREFIX_${component_name}}_COMPONENT_NAME = ${${__COMPONENT_PREFIX_${component_name}}_COMPONENT_NAME}")
    message(STATUS "[name-utils] ${__COMPONENT_PREFIX_${component_name}}_APP_NAME = ${${__COMPONENT_PREFIX_${component_name}}_APP_NAME}")
    message(STATUS "[name-utils] ${__COMPONENT_PREFIX_${component_name}}_SHORT_ENGINE_NAME = ${${__COMPONENT_PREFIX_${component_name}}_SHORT_ENGINE_NAME}")
    message(STATUS "[name-utils] ${__COMPONENT_PREFIX_${component_name}}_SHORT_API_NAME = ${${__COMPONENT_PREFIX_${component_name}}_SHORT_API_NAME}")
    message(STATUS "[name-utils] ${__COMPONENT_PREFIX_${component_name}}_SHORT_CLIENT_NAME = ${${__COMPONENT_PREFIX_${component_name}}_SHORT_CLIENT_NAME}")
    message(STATUS "[name-utils] ${__COMPONENT_PREFIX_${component_name}}_SHORT_GATEWAY_NAME = ${${__COMPONENT_PREFIX_${component_name}}_SHORT_GATEWAY_NAME}")
    message(STATUS "[name-utils] ${__COMPONENT_PREFIX_${component_name}}_SHORT_TOOL_PREFIX = ${${__COMPONENT_PREFIX_${component_name}}_SHORT_TOOL_PREFIX}")
    message(STATUS "[name-utils] ${__COMPONENT_PREFIX_${component_name}}_ENGINE_NAME = ${${__COMPONENT_PREFIX_${component_name}}_ENGINE_NAME}")
    message(STATUS "[name-utils] ${__COMPONENT_PREFIX_${component_name}}_API_NAME = ${${__COMPONENT_PREFIX_${component_name}}_API_NAME}")
    message(STATUS "[name-utils] ${__COMPONENT_PREFIX_${component_name}}_CLIENT_NAME = ${${__COMPONENT_PREFIX_${component_name}}_CLIENT_NAME}")
    message(STATUS "[name-utils] ${__COMPONENT_PREFIX_${component_name}}_GATEWAY_NAME = ${${__COMPONENT_PREFIX_${component_name}}_GATEWAY_NAME}")
    message(STATUS "[name-utils] ${__COMPONENT_PREFIX_${component_name}}_TOOL_PREFIX = ${${__COMPONENT_PREFIX_${component_name}}_TOOL_PREFIX}")
    message(STATUS "[name-utils] ${__COMPONENT_PREFIX_${component_name}}_INSTALL_PREFIX = ${${__COMPONENT_PREFIX_${component_name}}_INSTALL_PREFIX}")
endmacro()