macro(define_common_names prefix application_name)
    set(${prefix}_APP_NAME ${application_name})
    set(${prefix}_ENGINE_NAME ${application_name}-${ASSFIRE_APP_ENGINE_SUFFIX})
    set(${prefix}_PROTO_BINDING_NAME ${application_name}-${ASSFIRE_APP_PROTO_BINDING_SUFFIX})
    set(${prefix}_CLIENT_NAME ${application_name}-${ASSFIRE_APP_CLIENT_SUFFIX})
    set(${prefix}_REVERSE_PROXY_NAME ${application_name}-${ASSFIRE_APP_REVERSE_PROXY_SUFFIX})

    message(STATUS "[name-utils] Variables defined:")
    message(STATUS "[name-utils] ${prefix}_APP_NAME = ${${prefix}_APP_NAME}")
    message(STATUS "[name-utils] ${prefix}_ENGINE_NAME = ${${prefix}_ENGINE_NAME}")
    message(STATUS "[name-utils] ${prefix}_PROTO_BINDING_NAME = ${${prefix}_PROTO_BINDING_NAME}")
    message(STATUS "[name-utils] ${prefix}_CLIENT_NAME = ${${prefix}_CLIENT_NAME}")
    message(STATUS "[name-utils] ${prefix}_REVERSE_PROXY_NAME = ${${prefix}_REVERSE_PROXY_NAME}")
endmacro()