apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{.Release.Name}}-ca
  namespace: {{.Release.Namespace}}
spec:
  isCA: true
  commonName: {{.Release.Name}}-ca
  secretName: {{.Values.secret.name}}
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: {{.Release.Name}}-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  subject:
    organizations:
      - assfire.org
  dnsNames:
    - assfire.org